services:
  db:
    image:  mtiahrt/flea-market-db:1.0.0
    ports:
        - '5432:5432'
  app:
    image: mtiahrt/flea-market-be-app:1.0.0
    environment:
      POSTGRES_PORT: 5432
      PORT: 8080
      POSTGRES_PASSWORD: 'postgres'
      DEVELOPMENT: 'true'
      POSTGRES_SCHEMA: 'public'
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST: 'db'
    ports:
        - '8080:8080'
    depends_on:
        - db